name: ğŸ§ª Run tests and upload coverage

on: push

permissions:
  contents: read

jobs:
  test:
    name: ğŸ‘¨ğŸ¿â€ğŸ”¬ Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          fetch-depth: 2
          persist-credentials: false
      - name: Set up Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run coverage
        continue-on-error: true

      - name: Install dependencies in a subdirectory
        run: npm install
        working-directory: ./packages/cfsite
      - name: Run tests
        run: npm run coverage
        working-directory: ./packages/cfsite
      - name: Upload results to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
